## 선형대수 연산 
- 행렬 내적 

In [ ]:
import numpy as np 

A = np.array([[1, 2, 3], [4, 5, 6]]) # (2, 3)
B = np.array([[7, 8], [9, 10], [11, 12]]) # (3, 2)

dot_array = np.dot(A,B)
print(dot_array)

[[ 58  64]
 [139 154]]


- 전치 행렬

In [4]:
A = np.array([[1,2], [3, 4]])
transpose_mat = np.transpose(A)
print(transpose_mat)

B = np.array([[5, 6, 7], [8, 9, 10]])
transpose_mat = np.transpose(B)
print(transpose_mat)

[[1 3]
 [2 4]]
[[ 5  8]
 [ 6  9]
 [ 7 10]]
