## Numpy ndarray 개요

In [2]:
import numpy as np 

### shape, type

In [11]:
list1 = [1, 2, 3] #1차원 
print("List1 type :", type(list1))
array1 = np.array(list1)
print("Array1 type :", type(array1))
print("array1 array 형태 :", array1.shape)
print("")

array2 = np.array([[1, 2, 3], 
                   [4, 5, 6]]) #2차원
print("array2 type :", type(array2))
print("array2 array 형태 :", array2.shape)

print("")
array3 = np.array([[1, 2, 3]]) #2차원 
print("array3 type :", type(array3))
print("array3 array 형태 :", array3.shape)

List1 type : <class 'list'>
Array1 type : <class 'numpy.ndarray'>
array1 array 형태 : (3,)

array2 type : <class 'numpy.ndarray'>
array2 array 형태 : (2, 3)

array3 type : <class 'numpy.ndarray'>
array3 array 형태 : (1, 3)


### ndim : 차원

In [14]:
print('array1 : {:0}차원, array2 : {:1}차원, array3 : {:2}차원'.format(array1.ndim, array2.ndim, array3.ndim))

array1 : 1차원, array2 : 2차원, array3 :  2차원


## ndarray의 데이터 타입

In [15]:
list1 = [1, 2, 3]
array1 = np.array(list1)

print(type(array1))
print(array1, array1.dtype)

<class 'numpy.ndarray'>
[1 2 3] int64


In [ ]:
# 리스트안에는 동일한 데이터 타입의 값이 들어가야함 

list2 = [1, 2, 'test']
array2 = np.array(list2)
print(array2, array2.dtype)

list3 = [1, 2, 3.0]
array3 = np.array(list3)
print(array3, array3.dtype)

['1' '2' 'test'] <U21
[1. 2. 3.] float64


In [ ]:
array_int = np.array([1, 2, 3])
array_float = array_int.astype('float64') # array_int.astype(np.float64)
print(array_float, array_float.dtype)

array_int1 = array_float.astype('int32')
print(array_int1, array_int1.dtype)

array_float1 = np.array([1.1, 2.1, 3.1])
array_int2 = array_float1.astype('int32')
print(array_int2, array_int2.dtype)

[1. 2. 3.] float64
[1 2 3] int32
[1 2 3] int32


### ndarray를 편리하게 생성하기 - arange, zeros, ones 

In [22]:
#arange : 일정한 간격의 수열 생성
sequence_array = np.arange(10)
print(sequence_array)
print(sequence_array.dtype, sequence_array.shape)

[0 1 2 3 4 5 6 7 8 9]
int64 (10,)


In [23]:
# zeros : 모든 원소가 0으로 채워진 배열 생성 
zero_array = np.zeros((3, 2), dtype='int32')
print(zero_array)
print(zero_array.dtype, zero_array.shape)

[[0 0]
 [0 0]
 [0 0]]
int32 (3, 2)


In [24]:
#ones : 모든 원소가 1로 채워진 배열 생성
one_array = np.ones((2, 3), dtype= 'int32')
print(one_array)
print(one_array.dtype, one_array.shape)

[[1 1 1]
 [1 1 1]]
int32 (2, 3)


### reshape()

In [31]:
array1 = np.arange(10)

# (2, 5) shape으로 변환
array2 = array1.reshape(2, 5) # array1.reshape((2, 5))
print(array2)

# (5, 2) shape으로 변환
array3 = array1.reshape(5, 2)
print(array3)

[[0 1 2 3 4]
 [5 6 7 8 9]]
[[0 1]
 [2 3]
 [4 5]
 [6 7]
 [8 9]]


In [28]:
# 요소가 배열에 맞아야함 
# array3 = array1.reshape(4, 3) # 오류남

In [ ]:
array1 = np.arange(10)
array4 = array1.reshape(-1,5) # -1은 가변적으로 설정됨 
print(array4)
print(array4.shape)

array5 = array1.reshape(5, -1)
print(array5)

[[0 1 2 3 4]
 [5 6 7 8 9]]
(2, 5)
[[0 1]
 [2 3]
 [4 5]
 [6 7]
 [8 9]]


In [42]:
array1 = np.arange(8)
array3d = array1.reshape((2, 2, 2)) # 3차원 배열로 변환
print('array3d :', array3d.tolist())

array6 = array3d.reshape(-1, 1) # 3차원 -> 2차원 변환 
print('array6 :', array6.tolist())
print(array6.shape)

array7 = array1.reshape(-1 ,1) # 1차원 -> 2차원 변환 
print('array7 :', array7.tolist())
print(array7.shape)


array3d : [[[0, 1], [2, 3]], [[4, 5], [6, 7]]]
array6 : [[0], [1], [2], [3], [4], [5], [6], [7]]
(8, 1)
array7 : [[0], [1], [2], [3], [4], [5], [6], [7]]
(8, 1)


In [44]:
array1d = array3d.reshape(-1, ) # 3차원 -> 1차원 변환
print('array1d :', array1d.tolist())

array1d : [0, 1, 2, 3, 4, 5, 6, 7]
