### 넘파이 ndarray의 데이터 세트 선택하기 - indexing 
- 단일인덱싱

In [5]:
import numpy as np 

array1 = np.arange(start=1, stop=10)
print(array1)

value = array1[2]
print(value)
print(type(value))
print('맨 뒤의 값 :', array1[-1], '맨 뒤에서 두번째 값 :', array1[-2])

[1 2 3 4 5 6 7 8 9]
3
<class 'numpy.int64'>
맨 뒤의 값 : 9 맨 뒤에서 두번째 값 : 8


In [6]:
array1[0] = 9 
array1[8] = 0
print(array1)

[9 2 3 4 5 6 7 8 0]


In [10]:
array1d = np.arange(1, 10)
array2d = array1d.reshape(3, 3)
print(array2d)

print(array2d[0, 0])
print(array2d[1, 2])

[[1 2 3]
 [4 5 6]
 [7 8 9]]
1
6


- 슬라이싱 

In [15]:
array3 = array1d[0:3]
print(array3)

array4 = array1d[:3]
print(array4)

array2d = array1d.reshape(3, 3)
print(array2d)
array2d[0:2, 0:2]
array2d[1:3, :]


[1 2 3]
[1 2 3]
[[1 2 3]
 [4 5 6]
 [7 8 9]]


array([[4, 5, 6],
       [7, 8, 9]])

- 팬시 인덱싱 

In [16]:
array1d = np.arange(start=1, stop=10)
array2d = array1d.reshape(3,3)
print(array2d)

array3 = array2d[[0,1], 2]
print('array2d[[0,1], 2] => ',array3.tolist())

array4 = array2d[[0,1], 0:2]
print('array2d[[0,1], 0:2] => ',array4.tolist())

array5 = array2d[[0,1]]
print('array2d[[0,1]] => ',array5.tolist())

[[1 2 3]
 [4 5 6]
 [7 8 9]]
array2d[[0,1], 2] =>  [3, 6]
array2d[[0,1], 0:2] =>  [[1, 2], [4, 5]]
array2d[[0,1]] =>  [[1, 2, 3], [4, 5, 6]]


- 불린 인덱싱

In [17]:
array1d = np.arange(start=1, stop=10)
print(array1d)
# [ ] 안에 array1d > 5 Boolean indexing을 적용 
array3 = array1d[array1d > 5]
print('array1d > 5 불린 인덱싱 결과 값 :', array3)

[1 2 3 4 5 6 7 8 9]
array1d > 5 불린 인덱싱 결과 값 : [6 7 8 9]


In [18]:
array1d > 5

array([False, False, False, False, False,  True,  True,  True,  True])

In [19]:
val = array1d > 5
print(val, type(val), val.shape)

[False False False False False  True  True  True  True] <class 'numpy.ndarray'> (9,)


In [20]:
boolean_indexes = np.array([False, False, False, False, False,  True,  True,  True,  True])
array3 = array1d[boolean_indexes]
print('불린 인덱스로 필터링 결과 :', array3)

불린 인덱스로 필터링 결과 : [6 7 8 9]


In [22]:
array1d = np.arange(start=1, stop=10)
target = []
#불린 인덱싱을 적용하지 않았을 경우 
for i in range(0, 9):
    if array1d[i] > 5:
        target.append(array1d[i])

array_selected = np.array(target)
print(array_selected)
print(type(array_selected))


[6 7 8 9]
<class 'numpy.ndarray'>
