## 행렬의 정렬 -sort(), argsort()
- 행렬 정렬

In [4]:
import numpy as np 

org_array = np.array([3, 1, 9, 5])

#np.sort() 로 정렬 
sort_array1 = np.sort(org_array)
print(sort_array1) # 정렬 후 
print(org_array) # 정렬 전 
print()
# ndarray.sort( )로 정렬
sort_array2 = org_array.sort()
print(sort_array2) # 정렬 후
print(org_array) # 호출 후 원본 배열 


[1 3 5 9]
[3 1 9 5]

None
[1 3 5 9]


In [2]:
# 내림차순 
sort_array1_dec = np.sort(sort_array1)[::-1]
print(sort_array1_dec)

[9 5 3 1]


In [3]:
# 2차원 np.sort()
array2d = np.array([[8, 12], 
                   [7, 1 ]])

sort_array2d_axis0 = np.sort(array2d, axis=0)
print('로우 방향으로 정렬:\n', sort_array2d_axis0)

sort_array2d_axis1 = np.sort(array2d, axis=1)
print('컬럼 방향으로 정렬:\n', sort_array2d_axis1)

로우 방향으로 정렬:
 [[ 7  1]
 [ 8 12]]
컬럼 방향으로 정렬:
 [[ 8 12]
 [ 1  7]]


- 정렬 행렬의 인덱스 반환 argsort()

In [5]:
org_array = np.array([ 3, 1, 9, 5]) 
sort_indices = np.argsort(org_array)
print(type(sort_indices))
print('행렬 정렬 시 원본 배열의 인덱스:', sort_indices)

<class 'numpy.ndarray'>
행렬 정렬 시 원본 배열의 인덱스: [1 0 3 2]


In [6]:
sort_array1_desc = np.sort(org_array)[::-1]
print ('내림차순으로 정렬:', sort_array1_desc) 

내림차순으로 정렬: [9 5 3 1]


In [7]:
name_array = np.array(['John', 'Mike', 'Sarah', 'Kate', 'Samuel'])
score_array= np.array([78, 95, 84, 98, 88])

sort_indices_asc = np.argsort(score_array)
print('성적 오름차순 정렬 시 score_array의 인덱스:', sort_indices_asc)
print('성적 오름차순으로 name_array의 이름 출력:', name_array[sort_indices_asc])

성적 오름차순 정렬 시 score_array의 인덱스: [0 2 4 1 3]
성적 오름차순으로 name_array의 이름 출력: ['John' 'Sarah' 'Samuel' 'Mike' 'Kate']
